### ISSUE TITLE
Support renaming directories

### ISSUE THREAD

**Issue by jpfourny** [palantir/hadoop-crypto#100]
For this to work with tools like Spark, support is required for renaming directories. Currently, EncryptedFileSystem naively assumes the path being renamed is a regular file and barfs when it cannot find a key material for the directory. This is related to "Recursive delete support #93", in that there appears to be a general lack of consideration for recursive directory operations.

**Comment by ellisjoe** [comment]
The issue with the batch operations is that we don't have a way to atomically update every `KeyStorageStrategy`. If you're just using the `FileKeyStorageStrategy` we could potentially make a specific `EncryptedFileSystem` that uses the `FileKeyStorageStrategy` directly rather than being pluggable. It can then rely on the `FileSystem` rename and delete calls rather than the `KeyStorageStrategy` methods to move `KeyMaterial` around.

**Comment by ellisjoe** [comment]
@jpfourny released https://github.com/palantir/hadoop-crypto/releases/tag/2.4.0 which should fix your issues
